### ISSUE TITLE
Preview page

### ISSUE THREAD

**Issue by GhazanfarMir** [Atnic/laravel-light-bootstrap-dashboard#1]
Would be nice to have a preview page where we can see this in action before downloading/installing.

**Comment by frdteknikelektro** [comment]
Working on it!
But this is just simple replacement of laravel auth and home.

**Comment by frdteknikelektro** [comment]
![localhost_8000_home](https://user-images.githubusercontent.com/14815819/33922278-4aeb4050-dffc-11e7-8228-9a1e0077c868.png)
![localhost_8000_register](https://user-images.githubusercontent.com/14815819/33922279-4b2a1c4e-dffc-11e7-9730-980aaa47ca9c.png)
![localhost_8000_login](https://user-images.githubusercontent.com/14815819/33922280-4b6d845c-dffc-11e7-9c43-f3130f8e5ed4.png)
